### PR TITLE
direct root page to /reminders 

### LINKED ISSUE #2: Adjust Root to Redirect to ‘/reminders’
When the user visits the root of the application, they should be redirected to '/reminders' and should see a list of all reminders on the page. This means making a hopefully small adjustment to your router.js file.

**Hot Tip**: This will make your previous test fail (if you had it passing). Make the necessary changes in the test(s).

### PR DESCRIPTION
**Pull request by pescel**
closes #2 

## Purpose
 Rerouting the root page to the '/reminders' page in order to display the list of reminders. 

## Approach

 By changing the path in our 'route.js' file to '/reminders' and adding a transitionTo() method in the 'index.js' route file, we redirect the root page to the correct page to display the list. We also adjusted the first test in order to make it pass by adding '/reminders'. 

### Learning

Using Ember docs. 

### Test coverage 

Adjusted unit and integration tests to pass.

### CODE REVIEW

File: app/router.js [hunk 1]
```diff
@@ -7,8 +7,7 @@ const Router = Ember.Router.extend({
 });
 
 Router.map(function() {
-//  this.route('reminders');
-  this.route('reminders', { path: '/' });
+  this.route('reminders', { path: '/reminders' });
```
Comment (martensonbj) [inline app/router.js]: The path on the right hand side here is redundant - if it matches the same string as 'reminders' Ember knows to go there by default. Modify this to just be `this.route('reminders');`

**Review by martensonbj — CHANGES_REQUESTED** [review]
Small change!

**Comment by stephanieea** [comment]
@martensonbj The unnecessariness is gone!

**Review by martensonbj — APPROVED** [review]
